import { Router } from 'express';
import { accountsRouter } from './modules/accounts/accounts.routes';
import { appointmentsRouter } from './modules/appointments/appointments.routes';
import { authRouter } from './modules/auth/auth.routes';
import { branchesRouter } from './modules/branches/branches.routes';
import { bundlesRouter } from './modules/bundles/bundles.routes';
import { categoriesRouter } from './modules/categories/categories.routes';
import { clinicalRecordsRouter } from './modules/clinical-records/clinical-records.routes';
import { companyRouter } from './modules/company/company.routes';
import { consultationsRouter } from './modules/consultations/consultations.routes';
import { doctorsRouter } from './modules/doctors/doctors.routes';
import { expensesRouter } from './modules/expenses/expenses.routes';
import { healthRouter } from './modules/health/health.routes';
import { inventoryRouter } from './modules/inventory/inventory.routes';
import { journalRouter } from './modules/journal/journal.routes';
import { stockDocumentsRouter } from './modules/inventory/stock-documents.routes';
import { manufacturingRouter } from './modules/manufacturing/manufacturing.routes';
import { patientsRouter } from './modules/patients/patients.routes';
import { prescriptionsRouter } from './modules/prescriptions/prescriptions.routes';
import { productsRouter } from './modules/products/products.routes';
import { reportsRouter } from './modules/reports/reports.routes';
import { returnsRouter } from './modules/returns/returns.routes';
import { salesRouter } from './modules/sales/sales.routes';
import { staffRouter } from './modules/staff/staff.routes';
import { suppliersRouter } from './modules/suppliers/suppliers.routes';

export const apiRouter = Router();

apiRouter.use(healthRouter);
apiRouter.use(authRouter);
apiRouter.use(branchesRouter);
apiRouter.use(companyRouter);
apiRouter.use(staffRouter);
apiRouter.use(categoriesRouter);
apiRouter.use(productsRouter);
apiRouter.use(bundlesRouter);
apiRouter.use(suppliersRouter);
apiRouter.use(accountsRouter);
apiRouter.use(stockDocumentsRouter);
apiRouter.use(inventoryRouter);
apiRouter.use(manufacturingRouter);
apiRouter.use(patientsRouter);
apiRouter.use(doctorsRouter);
apiRouter.use(appointmentsRouter);
apiRouter.use(consultationsRouter);
apiRouter.use(clinicalRecordsRouter);
apiRouter.use(prescriptionsRouter);
apiRouter.use(salesRouter);
apiRouter.use(returnsRouter);
apiRouter.use(journalRouter);
apiRouter.use(expensesRouter);
apiRouter.use(reportsRouter);
